# see https://aider.chat/docs/config/aider_conf.html
#

chat-language: en

# NOTE, that the part before the first slash is for Aider to know the provider,
# the rest will be passed to the provider as model ID
alias:
  - gemini-pro:gemini/gemini-2.5-pro
#  - gemini-pro:gemini/gemini-2.5-pro-preview-03-25
  - ionos-gpt-120b:openai/openai/gpt-oss-120b
  - ionos-mistral-24b:openai/mistralai/Mistral-Small-24B-Instruct


