# support scrollwheel scrollback
set -g mouse on

# Change the background to a dark grey and text to white
set -g status-bg "#1e1e2e"
set -g status-fg "#cdd6f4"

# Highlight the active window with a different color (e.g., Purple)
set -g window-status-current-style bg=#cba6f7,fg=#1e1e2e,bold

# colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# history
set -g history-limit 50000

