theme = "iroaseta"

[keys.normal]
"C-c" = ["keep_primary_selection", "collapse_selection"]

[keys.insert]
"C-c" = "normal_mode"

[keys.select]
"C-c" = ["normal_mode", "keep_primary_selection", "collapse_selection"]

[editor]
# for Markdown linebreaks
trim-trailing-whitespace = false

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
# not implemented, see https://github.com/helix-editor/helix/issues/2719
#space = "trailing"
